Thread try
jose-ls/fibonacci pull request #25
Opened 2021-02-07 16:31 UTC by jose-ls

2021-02-07 16:39 UTC, stoyicker requested changes
he sido magnanimo

2021-02-07 16:39 UTC, stoyicker commented on src/main/java/org/jose/Base.java
> +
??

2021-02-07 16:39 UTC, stoyicker commented on src/main/java/org/jose/Base.java
> +
esta linea sobra

2021-02-07 16:39 UTC, stoyicker commented on src/main/java/org/jose/FibonacciBottomUp.java
> +
esta linea sobra

2021-02-07 16:39 UTC, stoyicker commented on src/main/java/org/jose/FibonacciBottomUp.java
> +        if (number == 1 || number == 0) {
esto me hace mucha gracia. aqui tienes `if (number == 1 || number == 0)` pero en otro sitio tienes `if (number < 2)` (que me gusta mas por cierto). decidete tio

2021-02-07 16:39 UTC, stoyicker commented on src/main/java/org/jose/FibonacciConMetodo.java
> + * Implementación interface Fibonacci con tiempo.
puedes tener cambios en la documentacion si son relevantes, esto es ir de incorrecto a incorrecto

2021-02-07 16:39 UTC, stoyicker commented on src/main/java/org/jose/FibonacciConTiempo.java
> +
sobra

2021-02-07 16:39 UTC, stoyicker commented on src/main/java/org/jose/FibonacciConTiempo.java
> +     *
sobra

2021-02-07 16:39 UTC, stoyicker commented on src/main/java/org/jose/FibonacciRecursivoMemorizacion.java
> +        if (number == 0) {
este `if` sobra

2021-02-07 16:39 UTC, stoyicker commented on src/main/java/org/jose/Impresora.java
> +public class Impresora implements ResultListener {
`ImpresoraDeResultados` :>(

2021-02-08 11:11 UTC, stoyicker requested changes
vamos progresando

2021-02-08 11:11 UTC, stoyicker commented on src/main/java/org/jose/FibonacciBottomUp.java
> +     * Campo de la clase.
solo para que lo sepas, sin poner que esto es un campo ya te sale que esto es un campo cuando generas el javadoc

2021-02-08 11:11 UTC, stoyicker commented on src/main/java/org/jose/FibonacciBottomUp.java
> +            resultListener.onResult(1);
aqui tienes un bug. fijate:
```
if (number < 2) {
  resultListener.onResult(1);
}
if (number > 0) {
  for (int i = 2; i <= n; i++) { 
    for (int i = 2; i <= number; i++) {
      ...
```
si el numero es 1, entras a los dos `ifs`. usa `else` o `return` para evitarlo

2021-02-08 11:11 UTC, stoyicker commented on src/main/java/org/jose/FibonacciBottomUp.java
> +            for (int i = 2; i <= number; i++) {
no te hace falta `if (number > 0)` porque en el `for` tu condicion es `i <= number`. si `number` es 0 o menor el for nunca va a empezar puesto quue el valor inicial de `i` es 2 y 2 es mayor que 0

2021-02-08 11:11 UTC, stoyicker commented on src/main/java/org/jose/FibonacciRecursivo.java
> +        if (number == 1 || number == 0) {
que uses el mismo `if` en todas partes

2021-02-08 11:11 UTC, stoyicker commented on src/main/java/org/jose/FibonacciRecursivo.java
> +            resultListener.onResult(1);
mira aqui si has usado bien el `else` para evitar mas logica si ya has notificado un resultado

2021-02-08 11:11 UTC, stoyicker commented on src/main/java/org/jose/FibonacciRecursivoMemorizacion.java
> +            resultListener.onResult(1);
aqui tambien te falta evitar mas logica puesto que ya has notificado tu resultado

2021-02-08 21:00 UTC, jose-ls commented on src/main/java/org/jose/FibonacciBottomUp.java
> +     * Campo de la clase.
Estoy trabajando en ir mejorandola poco a poco

2021-02-09 10:45 UTC, stoyicker requested changes

2021-02-09 10:45 UTC, stoyicker commented on src/main/java/org/jose/FibonacciBottomUp.java
> +            for (int i = 2; i <= number; i++) {
parate a leer el codigo para entender lo que digo y deja de cambiar cosas al tuntun a ver si aciertas

2021-02-09 10:45 UTC, stoyicker commented on src/main/java/org/jose/FibonacciRecursivo.java
> +            if (number >= 2) {
pero vamos a ver tio, si estas aqui es porque arriba `number < 2` era `false`. por tanto, aqui, por narices, `number >= 2` **siempre es true**

2021-02-09 14:34 UTC, stoyicker commented on src/main/java/org/jose/FibonacciBottomUp.java
> +        for (int i = 2; i <= number; i++) {
sin `if`s y solo con una salida de resultados. esta es probablemente la mejor implementacion posible para este metodo. muy bien

2021-02-09 14:38 UTC, stoyicker commented on src/main/java/org/jose/FibonacciRecursivoMemorizacion.java
>          } else {
mejor que 
`else {
  if {`
usa
`else if {`
es un nivel de indentacion menos

2021-02-09 14:38 UTC, stoyicker requested changes
ya queda menos

2021-02-10 12:57 UTC, stoyicker approved these changes

2021-02-10 12:57 UTC, merged